# Generated by Django 5.1.4 on 2025-01-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=6, max_length=100),
            preserve_default=False,
        ),
    ]
